name: dartweave
description: Class creation CLI
version: 0.0.2
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^10.0.1
  args: ^2.5.0
  cli_completion: ^0.5.1
  equatable: ^2.0.8
  mason_logger: ^0.3.0
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0

executables:
  dartweave:
